sonar.projectKey=jvleeuwen_SalonBalance
sonar.organization=jvleeuwen
sonar.projectName=SalonBalance
sonar.projectVersion=1.0

sonar.sources=app,routes,database
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/**
sonar.scanner.skipJreProvisioning=true
